package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CardDetails generated by hbm2java
 */
@Entity
@Table(name="card_details"
    ,catalog="ghecommerceappdb"
    , uniqueConstraints = @UniqueConstraint(columnNames="card_number") 
)
public class CardDetails  implements java.io.Serializable {


     private Integer id;
     private CreditOrDebitCardType creditOrDebitCardType;
     private Customer customer;
     private String cardNumber;
     private String cardName;
     private int expYear;
     private byte expMonth;
     private boolean isDefault;
     private Set customerOrders = new HashSet(0);

    public CardDetails() {
    }

	
    public CardDetails(CreditOrDebitCardType creditOrDebitCardType, Customer customer, String cardNumber, String cardName, int expYear, byte expMonth, boolean isDefault) {
        this.creditOrDebitCardType = creditOrDebitCardType;
        this.customer = customer;
        this.cardNumber = cardNumber;
        this.cardName = cardName;
        this.expYear = expYear;
        this.expMonth = expMonth;
        this.isDefault = isDefault;
    }
    public CardDetails(CreditOrDebitCardType creditOrDebitCardType, Customer customer, String cardNumber, String cardName, int expYear, byte expMonth, boolean isDefault, Set customerOrders) {
       this.creditOrDebitCardType = creditOrDebitCardType;
       this.customer = customer;
       this.cardNumber = cardNumber;
       this.cardName = cardName;
       this.expYear = expYear;
       this.expMonth = expMonth;
       this.isDefault = isDefault;
       this.customerOrders = customerOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="card_type_id", nullable=false)
    public CreditOrDebitCardType getCreditOrDebitCardType() {
        return this.creditOrDebitCardType;
    }
    
    public void setCreditOrDebitCardType(CreditOrDebitCardType creditOrDebitCardType) {
        this.creditOrDebitCardType = creditOrDebitCardType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="card_number", unique=true, nullable=false, length=16)
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    
    @Column(name="card_name", nullable=false, length=45)
    public String getCardName() {
        return this.cardName;
    }
    
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    
    @Column(name="exp_year", nullable=false)
    public int getExpYear() {
        return this.expYear;
    }
    
    public void setExpYear(int expYear) {
        this.expYear = expYear;
    }

    
    @Column(name="exp_month", nullable=false)
    public byte getExpMonth() {
        return this.expMonth;
    }
    
    public void setExpMonth(byte expMonth) {
        this.expMonth = expMonth;
    }

    
    @Column(name="is_default", nullable=false)
    public boolean isIsDefault() {
        return this.isDefault;
    }
    
    public void setIsDefault(boolean isDefault) {
        this.isDefault = isDefault;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cardDetails")
    public Set getCustomerOrders() {
        return this.customerOrders;
    }
    
    public void setCustomerOrders(Set customerOrders) {
        this.customerOrders = customerOrders;
    }




}


