package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="ghecommerceappdb"
)
public class Country  implements java.io.Serializable {


     private String id;
     private String countryName;
     private Set addresses = new HashSet(0);

    public Country() {
    }

	
    public Country(String id, String countryName) {
        this.id = id;
        this.countryName = countryName;
    }
    public Country(String id, String countryName, Set addresses) {
       this.id = id;
       this.countryName = countryName;
       this.addresses = addresses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=50)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="country_name", nullable=false, length=45)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }




}


