package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeLoginHistory generated by hbm2java
 */
@Entity
@Table(name="employee_login_history"
    ,catalog="ghecommerceappdb"
)
public class EmployeeLoginHistory  implements java.io.Serializable {


     private int id;
     private Employee employee;
     private Date dateTime;

    public EmployeeLoginHistory() {
    }

    public EmployeeLoginHistory(int id, Employee employee, Date dateTime) {
       this.id = id;
       this.employee = employee;
       this.dateTime = dateTime;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_time", nullable=false, length=19)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


