package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FirstLevelAccess generated by hbm2java
 */
@Entity
@Table(name="first_level_access"
    ,catalog="ghecommerceappdb"
    , uniqueConstraints = @UniqueConstraint(columnNames="role") 
)
public class FirstLevelAccess  implements java.io.Serializable {


     private Integer id;
     private Role role;
     private boolean f1;
     private boolean f2;
     private boolean f3;
     private boolean f4;
     private boolean f5;
     private boolean f6;

    public FirstLevelAccess() {
    }

    public FirstLevelAccess(Role role, boolean f1, boolean f2, boolean f3, boolean f4, boolean f5, boolean f6) {
       this.role = role;
       this.f1 = f1;
       this.f2 = f2;
       this.f3 = f3;
       this.f4 = f4;
       this.f5 = f5;
       this.f6 = f6;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role", unique=true, nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="f1", nullable=false)
    public boolean isF1() {
        return this.f1;
    }
    
    public void setF1(boolean f1) {
        this.f1 = f1;
    }

    
    @Column(name="f2", nullable=false)
    public boolean isF2() {
        return this.f2;
    }
    
    public void setF2(boolean f2) {
        this.f2 = f2;
    }

    
    @Column(name="f3", nullable=false)
    public boolean isF3() {
        return this.f3;
    }
    
    public void setF3(boolean f3) {
        this.f3 = f3;
    }

    
    @Column(name="f4", nullable=false)
    public boolean isF4() {
        return this.f4;
    }
    
    public void setF4(boolean f4) {
        this.f4 = f4;
    }

    
    @Column(name="f5", nullable=false)
    public boolean isF5() {
        return this.f5;
    }
    
    public void setF5(boolean f5) {
        this.f5 = f5;
    }

    
    @Column(name="f6", nullable=false)
    public boolean isF6() {
        return this.f6;
    }
    
    public void setF6(boolean f6) {
        this.f6 = f6;
    }




}


