package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderLine generated by hbm2java
 */
@Entity
@Table(name="order_line"
    ,catalog="ghecommerceappdb"
)
public class OrderLine  implements java.io.Serializable {


     private Integer id;
     private CustomerOrder customerOrder;
     private ProductItem productItem;
     private Promotion promotion;
     private int qty;
     private double price;

    public OrderLine() {
    }

	
    public OrderLine(CustomerOrder customerOrder, ProductItem productItem, int qty, double price) {
        this.customerOrder = customerOrder;
        this.productItem = productItem;
        this.qty = qty;
        this.price = price;
    }
    public OrderLine(CustomerOrder customerOrder, ProductItem productItem, Promotion promotion, int qty, double price) {
       this.customerOrder = customerOrder;
       this.productItem = productItem;
       this.promotion = promotion;
       this.qty = qty;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_order_id", nullable=false)
    public CustomerOrder getCustomerOrder() {
        return this.customerOrder;
    }
    
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_item_id", nullable=false)
    public ProductItem getProductItem() {
        return this.productItem;
    }
    
    public void setProductItem(ProductItem productItem) {
        this.productItem = productItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="promotion_id")
    public Promotion getPromotion() {
        return this.promotion;
    }
    
    public void setPromotion(Promotion promotion) {
        this.promotion = promotion;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


