package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="ghecommerceappdb"
)
public class Product  implements java.io.Serializable {


     private String id;
     private ProductCategory productCategory;
     private String name;
     private String description;
     private String imagePathOne;
     private String imagePathTwo;
     private boolean status;
     private Set productItems = new HashSet(0);

    public Product() {
    }

	
    public Product(String id, ProductCategory productCategory, String name, String description, String imagePathOne, String imagePathTwo, boolean status) {
        this.id = id;
        this.productCategory = productCategory;
        this.name = name;
        this.description = description;
        this.imagePathOne = imagePathOne;
        this.imagePathTwo = imagePathTwo;
        this.status = status;
    }
    public Product(String id, ProductCategory productCategory, String name, String description, String imagePathOne, String imagePathTwo, boolean status, Set productItems) {
       this.id = id;
       this.productCategory = productCategory;
       this.name = name;
       this.description = description;
       this.imagePathOne = imagePathOne;
       this.imagePathTwo = imagePathTwo;
       this.status = status;
       this.productItems = productItems;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=20)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public ProductCategory getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }

    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=225)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="image_path-one", nullable=false, length=225)
    public String getImagePathOne() {
        return this.imagePathOne;
    }
    
    public void setImagePathOne(String imagePathOne) {
        this.imagePathOne = imagePathOne;
    }

    
    @Column(name="image_path_two", nullable=false, length=225)
    public String getImagePathTwo() {
        return this.imagePathTwo;
    }
    
    public void setImagePathTwo(String imagePathTwo) {
        this.imagePathTwo = imagePathTwo;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set getProductItems() {
        return this.productItems;
    }
    
    public void setProductItems(Set productItems) {
        this.productItems = productItems;
    }




}


