package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductItem generated by hbm2java
 */
@Entity
@Table(name="product_item"
    ,catalog="ghecommerceappdb"
)
public class ProductItem  implements java.io.Serializable {


     private String id;
     private Product product;
     private String name;
     private String sku;
     private int qty;
     private double price;
     private String itemImgOnePath;
     private String itemImgTwoPath;
     private String itemImgThreePath;
     private boolean status;
     private String description;
     private Set wishLists = new HashSet(0);
     private Set reviews = new HashSet(0);
     private Set variationOptions = new HashSet(0);
     private Set orderLines = new HashSet(0);
     private Set shoppingCartItems = new HashSet(0);

    public ProductItem() {
    }

	
    public ProductItem(String id, Product product, String name, String sku, int qty, double price, String itemImgOnePath, String itemImgTwoPath, String itemImgThreePath, boolean status, String description) {
        this.id = id;
        this.product = product;
        this.name = name;
        this.sku = sku;
        this.qty = qty;
        this.price = price;
        this.itemImgOnePath = itemImgOnePath;
        this.itemImgTwoPath = itemImgTwoPath;
        this.itemImgThreePath = itemImgThreePath;
        this.status = status;
        this.description = description;
    }
    public ProductItem(String id, Product product, String name, String sku, int qty, double price, String itemImgOnePath, String itemImgTwoPath, String itemImgThreePath, boolean status, String description, Set wishLists, Set reviews, Set variationOptions, Set orderLines, Set shoppingCartItems) {
       this.id = id;
       this.product = product;
       this.name = name;
       this.sku = sku;
       this.qty = qty;
       this.price = price;
       this.itemImgOnePath = itemImgOnePath;
       this.itemImgTwoPath = itemImgTwoPath;
       this.itemImgThreePath = itemImgThreePath;
       this.status = status;
       this.description = description;
       this.wishLists = wishLists;
       this.reviews = reviews;
       this.variationOptions = variationOptions;
       this.orderLines = orderLines;
       this.shoppingCartItems = shoppingCartItems;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=20)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="name", nullable=false, length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="sku", nullable=false, length=60)
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="item_img_one_path", nullable=false, length=225)
    public String getItemImgOnePath() {
        return this.itemImgOnePath;
    }
    
    public void setItemImgOnePath(String itemImgOnePath) {
        this.itemImgOnePath = itemImgOnePath;
    }

    
    @Column(name="item_img_two_path", nullable=false, length=225)
    public String getItemImgTwoPath() {
        return this.itemImgTwoPath;
    }
    
    public void setItemImgTwoPath(String itemImgTwoPath) {
        this.itemImgTwoPath = itemImgTwoPath;
    }

    
    @Column(name="item_img_three_path", nullable=false, length=225)
    public String getItemImgThreePath() {
        return this.itemImgThreePath;
    }
    
    public void setItemImgThreePath(String itemImgThreePath) {
        this.itemImgThreePath = itemImgThreePath;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="description", nullable=false, length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productItem")
    public Set getWishLists() {
        return this.wishLists;
    }
    
    public void setWishLists(Set wishLists) {
        this.wishLists = wishLists;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productItem")
    public Set getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set reviews) {
        this.reviews = reviews;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="product_configuration", catalog="ghecommerceappdb", joinColumns = { 
        @JoinColumn(name="product_item_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="variation_option_id", nullable=false, updatable=false) })
    public Set getVariationOptions() {
        return this.variationOptions;
    }
    
    public void setVariationOptions(Set variationOptions) {
        this.variationOptions = variationOptions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productItem")
    public Set getOrderLines() {
        return this.orderLines;
    }
    
    public void setOrderLines(Set orderLines) {
        this.orderLines = orderLines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productItem")
    public Set getShoppingCartItems() {
        return this.shoppingCartItems;
    }
    
    public void setShoppingCartItems(Set shoppingCartItems) {
        this.shoppingCartItems = shoppingCartItems;
    }




}


