package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name="product_category"
    ,catalog="ghecommerceappdb"
)
public class ProductCategory  implements java.io.Serializable {


     private String id;
     private ProductCategory productCategory;
     private String name;
     private boolean status;
     private Set variations = new HashSet(0);
     private Set productCategories = new HashSet(0);
     private Set promotions = new HashSet(0);
     private Set products = new HashSet(0);

    public ProductCategory() {
    }

	
    public ProductCategory(String id, String name, boolean status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }
    public ProductCategory(String id, ProductCategory productCategory, String name, boolean status, Set variations, Set productCategories, Set promotions, Set products) {
       this.id = id;
       this.productCategory = productCategory;
       this.name = name;
       this.status = status;
       this.variations = variations;
       this.productCategories = productCategories;
       this.promotions = promotions;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=20)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_category_id")
    public ProductCategory getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productCategory")
    public Set getVariations() {
        return this.variations;
    }
    
    public void setVariations(Set variations) {
        this.variations = variations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productCategory")
    public Set getProductCategories() {
        return this.productCategories;
    }
    
    public void setProductCategories(Set productCategories) {
        this.productCategories = productCategories;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="promotion_category", catalog="ghecommerceappdb", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="promotion_id", nullable=false, updatable=false) })
    public Set getPromotions() {
        return this.promotions;
    }
    
    public void setPromotions(Set promotions) {
        this.promotions = promotions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productCategory")
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


