package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name="promotion"
    ,catalog="ghecommerceappdb"
)
public class Promotion  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private double discountRate;
     private Date startDate;
     private Date endDate;
     private boolean status;
     private Set productCategories = new HashSet(0);
     private Set orderLines = new HashSet(0);

    public Promotion() {
    }

	
    public Promotion(String name, String description, double discountRate, Date startDate, Date endDate, boolean status) {
        this.name = name;
        this.description = description;
        this.discountRate = discountRate;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
    }
    public Promotion(String name, String description, double discountRate, Date startDate, Date endDate, boolean status, Set productCategories, Set orderLines) {
       this.name = name;
       this.description = description;
       this.discountRate = discountRate;
       this.startDate = startDate;
       this.endDate = endDate;
       this.status = status;
       this.productCategories = productCategories;
       this.orderLines = orderLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=225)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="discount_rate", nullable=false, precision=22, scale=0)
    public double getDiscountRate() {
        return this.discountRate;
    }
    
    public void setDiscountRate(double discountRate) {
        this.discountRate = discountRate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", nullable=false, length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="promotion_category", catalog="ghecommerceappdb", joinColumns = { 
        @JoinColumn(name="promotion_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=false) })
    public Set getProductCategories() {
        return this.productCategories;
    }
    
    public void setProductCategories(Set productCategories) {
        this.productCategories = productCategories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="promotion")
    public Set getOrderLines() {
        return this.orderLines;
    }
    
    public void setOrderLines(Set orderLines) {
        this.orderLines = orderLines;
    }




}


