package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recovery generated by hbm2java
 */
@Entity
@Table(name="recovery"
    ,catalog="ghecommerceappdb"
)
public class Recovery  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private String recoveryCode;

    public Recovery() {
    }

    public Recovery(Customer customer, String recoveryCode) {
       this.customer = customer;
       this.recoveryCode = recoveryCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="recovery_code", nullable=false, length=50)
    public String getRecoveryCode() {
        return this.recoveryCode;
    }
    
    public void setRecoveryCode(String recoveryCode) {
        this.recoveryCode = recoveryCode;
    }




}


