package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="review"
    ,catalog="ghecommerceappdb"
)
public class Review  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private CustomerOrder customerOrder;
     private ProductItem productItem;
     private String commentTitle;
     private String comment;
     private int rate;
     private Date date;
     private Set reviewHelpfuls = new HashSet(0);

    public Review() {
    }

	
    public Review(Customer customer, CustomerOrder customerOrder, ProductItem productItem, String commentTitle, String comment, int rate, Date date) {
        this.customer = customer;
        this.customerOrder = customerOrder;
        this.productItem = productItem;
        this.commentTitle = commentTitle;
        this.comment = comment;
        this.rate = rate;
        this.date = date;
    }
    public Review(Customer customer, CustomerOrder customerOrder, ProductItem productItem, String commentTitle, String comment, int rate, Date date, Set reviewHelpfuls) {
       this.customer = customer;
       this.customerOrder = customerOrder;
       this.productItem = productItem;
       this.commentTitle = commentTitle;
       this.comment = comment;
       this.rate = rate;
       this.date = date;
       this.reviewHelpfuls = reviewHelpfuls;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customerOrder", nullable=false)
    public CustomerOrder getCustomerOrder() {
        return this.customerOrder;
    }
    
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product", nullable=false)
    public ProductItem getProductItem() {
        return this.productItem;
    }
    
    public void setProductItem(ProductItem productItem) {
        this.productItem = productItem;
    }

    
    @Column(name="comment_title", nullable=false, length=45)
    public String getCommentTitle() {
        return this.commentTitle;
    }
    
    public void setCommentTitle(String commentTitle) {
        this.commentTitle = commentTitle;
    }

    
    @Column(name="comment", nullable=false, length=1000)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="rate", nullable=false)
    public int getRate() {
        return this.rate;
    }
    
    public void setRate(int rate) {
        this.rate = rate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="review")
    public Set getReviewHelpfuls() {
        return this.reviewHelpfuls;
    }
    
    public void setReviewHelpfuls(Set reviewHelpfuls) {
        this.reviewHelpfuls = reviewHelpfuls;
    }




}


