package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShoppingCartItem generated by hbm2java
 */
@Entity
@Table(name="shopping_cart_item"
    ,catalog="ghecommerceappdb"
)
public class ShoppingCartItem  implements java.io.Serializable {


     private Integer id;
     private ProductItem productItem;
     private ShoppingCart shoppingCart;
     private int qty;
     private boolean selected;

    public ShoppingCartItem() {
    }

    public ShoppingCartItem(ProductItem productItem, ShoppingCart shoppingCart, int qty, boolean selected) {
       this.productItem = productItem;
       this.shoppingCart = shoppingCart;
       this.qty = qty;
       this.selected = selected;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_item_id", nullable=false)
    public ProductItem getProductItem() {
        return this.productItem;
    }
    
    public void setProductItem(ProductItem productItem) {
        this.productItem = productItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart_id", nullable=false)
    public ShoppingCart getShoppingCart() {
        return this.shoppingCart;
    }
    
    public void setShoppingCart(ShoppingCart shoppingCart) {
        this.shoppingCart = shoppingCart;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }

    
    @Column(name="selected", nullable=false)
    public boolean isSelected() {
        return this.selected;
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
    }




}


