package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name="system_user"
    ,catalog="ghecommerceappdb"
)
public class SystemUser  implements java.io.Serializable {


     private String userName;
     private Employee employee;
     private Role role;
     private String userPassword;
     private Date lastLogin;
     private Date createdDate;
     private Date lastUpdate;
     private boolean status;

    public SystemUser() {
    }

    public SystemUser(String userName, Employee employee, Role role, String userPassword, Date lastLogin, Date createdDate, Date lastUpdate, boolean status) {
       this.userName = userName;
       this.employee = employee;
       this.role = role;
       this.userPassword = userPassword;
       this.lastLogin = lastLogin;
       this.createdDate = createdDate;
       this.lastUpdate = lastUpdate;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="user_name", unique=true, nullable=false, length=20)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="user_password", nullable=false, length=45)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login", nullable=false, length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


