package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name="test"
    ,catalog="ghecommerceappdb"
)
public class Test  implements java.io.Serializable {


     private Integer idtest;
     private Date date;
     private String name;
     private Date dateTime;

    public Test() {
    }

    public Test(Date date, String name, Date dateTime) {
       this.date = date;
       this.name = name;
       this.dateTime = dateTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtest", unique=true, nullable=false)
    public Integer getIdtest() {
        return this.idtest;
    }
    
    public void setIdtest(Integer idtest) {
        this.idtest = idtest;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_time", length=19)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


