package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Variation generated by hbm2java
 */
@Entity
@Table(name="variation"
    ,catalog="ghecommerceappdb"
)
public class Variation  implements java.io.Serializable {


     private Integer id;
     private ProductCategory productCategory;
     private String name;
     private Set variationOptions = new HashSet(0);

    public Variation() {
    }

	
    public Variation(ProductCategory productCategory, String name) {
        this.productCategory = productCategory;
        this.name = name;
    }
    public Variation(ProductCategory productCategory, String name, Set variationOptions) {
       this.productCategory = productCategory;
       this.name = name;
       this.variationOptions = variationOptions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public ProductCategory getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="variation")
    public Set getVariationOptions() {
        return this.variationOptions;
    }
    
    public void setVariationOptions(Set variationOptions) {
        this.variationOptions = variationOptions;
    }




}


