package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VariationOption generated by hbm2java
 */
@Entity
@Table(name="variation_option"
    ,catalog="ghecommerceappdb"
)
public class VariationOption  implements java.io.Serializable {


     private Integer id;
     private Variation variation;
     private String value;
     private Set productItems = new HashSet(0);

    public VariationOption() {
    }

	
    public VariationOption(Variation variation, String value) {
        this.variation = variation;
        this.value = value;
    }
    public VariationOption(Variation variation, String value, Set productItems) {
       this.variation = variation;
       this.value = value;
       this.productItems = productItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="variation_id", nullable=false)
    public Variation getVariation() {
        return this.variation;
    }
    
    public void setVariation(Variation variation) {
        this.variation = variation;
    }

    
    @Column(name="value", nullable=false, length=45)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="product_configuration", catalog="ghecommerceappdb", joinColumns = { 
        @JoinColumn(name="variation_option_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="product_item_id", nullable=false, updatable=false) })
    public Set getProductItems() {
        return this.productItems;
    }
    
    public void setProductItems(Set productItems) {
        this.productItems = productItems;
    }




}


