package model;
// Generated Oct 22, 2024 5:07:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WishList generated by hbm2java
 */
@Entity
@Table(name="wish_list"
    ,catalog="ghecommerceappdb"
)
public class WishList  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private ProductItem productItem;

    public WishList() {
    }

    public WishList(Customer customer, ProductItem productItem) {
       this.customer = customer;
       this.productItem = productItem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_item", nullable=false)
    public ProductItem getProductItem() {
        return this.productItem;
    }
    
    public void setProductItem(ProductItem productItem) {
        this.productItem = productItem;
    }




}


